version: "3.8"

services:
  postgres:
    image: postgres:16-alpine #postgres 16 with alpine linux  -> because alpine is lightweight and more secure
    container_name: logistics_db
    restart: unless-stopped #Auto restart if crashes
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: logistics_engine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/infra/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
